// This file is auto-generated by setup-pinecone.js
        // Do not edit manually - run 'npm run setup-pinecone' to update

        export interface MaxValues {
        points: number;
        assists: number;
        rebounds: number;
        steals: number;
        blocks: number;
        turnovers: number;
        }

        export interface PlayerStats {
        points: number;
        rebounds: number;
        assists: number;
        steals: number;
        blocks: number;
        turnovers: number;
        fieldGoalPercentage: number;
        threePointPercentage: number;
        freeThrowPercentage: number;
        }

        // Auto-generated max values from dataset
        export const MAX_VALUES: MaxValues = {
        points: 30.388059701492537,
        assists: 7.361702127659575,
        rebounds: 11.91044776119403,
        steals: 1.4864864864864864,
        blocks: 1.164179104477612,
        turnovers: 3.5531914893617023,
        };

        // Normalization function
        export function normalizeAndVectorize(stats: PlayerStats): number[] {
        return [
            Math.min(stats.points / MAX_VALUES.points, 1),
            Math.min(stats.assists / MAX_VALUES.assists, 1),
            Math.min(stats.rebounds / MAX_VALUES.rebounds, 1),
            Math.min(stats.steals / MAX_VALUES.steals, 1),
            Math.min(stats.blocks / MAX_VALUES.blocks, 1),
            Math.min(stats.turnovers / MAX_VALUES.turnovers, 1),
            stats.fieldGoalPercentage,
            stats.threePointPercentage,
            stats.freeThrowPercentage
        ];
        }
    